# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooltrips', '__first__'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedForSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('school_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('schooltour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schooltrips.SchoolTourDetail')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('tourdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail')),
            ],
        ),
    ]
