# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0002_interestedforplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestedforplace',
            name='place',
        ),
    ]
