# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20160920_0933'),
        ('interested', '0003_remove_interestedforplace_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedforplace',
            name='placedetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail'),
        ),
    ]
