# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interested', '0005_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='date',
        ),
    ]
