# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Adventure', 'Adventure'), ('Hill Station', 'Hill Station'), ('Religious & Spiritual', 'religious & Spiritual'), ('Beaches', 'Beaches'), ('Wildlife', 'Wildlife')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTourDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=250, null=True)),
                ('tour_price', models.IntegerField(null=True)),
                ('number_days', models.CharField(max_length=250, null=True)),
                ('tour_detail', models.TextField(max_length=10000, null=True)),
                ('main_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='schooltrips')),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('exclusion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Exclusion')),
                ('inclusion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Inclusion')),
                ('placedetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
                ('statedetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.StateDetail')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='schooltrips')),
                ('tourdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltrips.SchoolTourDetail')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTourItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_day', models.IntegerField(null=True)),
                ('tour_itinerary', models.TextField(max_length=10000, null=True)),
                ('tour_stay', models.CharField(max_length=250, null=True)),
                ('tourdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltrips.SchoolTourDetail')),
            ],
        ),
        migrations.AddField(
            model_name='schooltourcategory',
            name='tourdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltrips.SchoolTourDetail'),
        ),
    ]
