# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deal_done', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_date', models.DateTimeField(null=True)),
                ('Meeting_attended_by', models.CharField(max_length=1024, null=True)),
                ('Meeting_Result', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intercity_travel', models.CharField(max_length=1024, null=True)),
                ('Local_travel', models.CharField(max_length=1024, null=True)),
                ('hotel_name', models.CharField(max_length=1024, null=True)),
                ('sightseeing', models.CharField(max_length=1024, null=True)),
                ('extraordinery_point', models.CharField(max_length=1024, null=True)),
                ('extra', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=1024, null=True)),
                ('tour_date', models.DateTimeField(null=True)),
                ('number_of_adult', models.IntegerField(null=True)),
                ('number_of_child', models.IntegerField(null=True)),
                ('Budget', models.IntegerField(null=True)),
                ('Needs', models.TextField(max_length=2048, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='tourinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.TourInfo'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tourinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.TourInfo'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tourinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offline.TourInfo'),
        ),
    ]
