# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourinfo',
            old_name='Budget',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='tourinfo',
            old_name='Needs',
            new_name='needs',
        ),
    ]
