# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBathroomImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
                ('facilitytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.FacilityType')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hotels')),
            ],
        ),
        migrations.CreateModel(
            name='HotelViewImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hotels')),
            ],
        ),
        migrations.CreateModel(
            name='TourepediaHotelRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_rating',
            new_name='star_rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='about_hotel',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='main_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='hotels'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tourepediahotelrating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AddField(
            model_name='hotelviewimg',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AddField(
            model_name='hotelroomimg',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AddField(
            model_name='hotelbathroomimg',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
