# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_facilitytype_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='hotelfacility',
            old_name='facilitytype',
            new_name='facility_type',
        ),
        migrations.RemoveField(
            model_name='hotelfacility',
            name='facility',
        ),
        migrations.AddField(
            model_name='hotelfacility',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AddField(
            model_name='facility',
            name='facilitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.FacilityType'),
        ),
    ]
