# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20160903_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='hotel',
        ),
    ]
