# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_facilitytype_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=240, null=True),
        ),
    ]
