# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
