# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='pub_date',
        ),
    ]
