# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_hotel_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='slug',
            new_name='slug1',
        ),
    ]
