# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20160906_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='slug1',
            new_name='slug',
        ),
    ]
