# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_auto_20160906_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbathroomimg',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='tourepediahotelrating',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='HotelBathroomImg',
        ),
        migrations.DeleteModel(
            name='TourepediaHotelRating',
        ),
    ]
