# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_auto_20160906_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Luxury', 'Luxury')], max_length=128, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_price',
            new_name='starting_price',
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
