# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20160906_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfacility',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='hotelfacility',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='facility_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Facility'),
        ),
        migrations.DeleteModel(
            name='HotelFacility',
        ),
    ]
