# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20160906_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='facility_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.FacilityType'),
        ),
    ]
