# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20160906_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprice',
            name='room_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
