# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_hotelprice_season_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='concerned_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mobile_number1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mobile_number2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
