# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_auto_20161211_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='starting_price',
        ),
    ]
