# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_remove_hotel_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprice',
            name='extra_person_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
