# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_hotel_starting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotelprice',
            name='season_extra_person_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
