# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveltriangle', '0058_auto_20161211_1824'),
        ('hotels', '0022_hotel_starting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=225, null=True)),
                ('room_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_confirmation_received', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
                ('tripdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=225, null=True)),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('price_paid', models.PositiveIntegerField(null=True)),
                ('flight_booked', models.BooleanField(default=False)),
                ('price_paid_for_flight', models.PositiveIntegerField(blank=True, default=0)),
                ('train_booked', models.BooleanField(default=False)),
                ('price_paid_for_train', models.PositiveIntegerField(blank=True, default=0)),
                ('tripdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_expences', models.PositiveIntegerField(blank=True, null=True)),
                ('tripdetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OtherBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('tripdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
    ]
