# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterbook', '0002_auto_20161217_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedhotel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
