# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0060_auto_20161215_1300'),
        ('afterbook', '0004_auto_20161217_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=225, null=True)),
                ('concerned_person', models.CharField(max_length=250, null=True)),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('price_paid', models.PositiveIntegerField(null=True)),
                ('tripdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookedtravel',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='bookedtravel',
            name='price_paid',
        ),
        migrations.RemoveField(
            model_name='bookedtravel',
            name='total_price',
        ),
        migrations.AddField(
            model_name='bookedhotel',
            name='payment_reciept',
            field=models.FileField(blank=True, null=True, upload_to='traveltriangle/payment_files'),
        ),
    ]
