# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afterbook', '0005_auto_20161217_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedhotel',
            old_name='trip_nights',
            new_name='hotel_nights',
        ),
    ]
