# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '__first__'),
        ('places', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Nature', 'Nature'), ('Romantic', 'Romantic'), ('Family', 'Family'), ('Hill Station', 'Hill Station'), ('Adventure', 'Adventure'), ('Religious & Spiritual', 'religious & Spiritual'), ('Beaches', 'Beaches'), ('Wildlife', 'Wildlife')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=250, null=True)),
                ('tour_price', models.IntegerField(null=True)),
                ('tour_tagline', models.CharField(max_length=250, null=True)),
                ('tour_detail', models.TextField(max_length=10000, null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('main_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='tours')),
                ('view', models.IntegerField(default=0, null=True)),
                ('slug', models.SlugField(null=True)),
                ('exclusion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.TourExclusion')),
                ('inclusion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.TourInclusion')),
                ('placedetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
                ('statedetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.StateDetail')),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='tours')),
                ('tourdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail')),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_day', models.IntegerField(null=True)),
                ('tour_itinerary', models.TextField(max_length=10000, null=True)),
                ('tour_stay', models.CharField(max_length=250, null=True)),
                ('tourdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail')),
            ],
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='tourdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail'),
        ),
    ]
