# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='exclusion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Exclusion'),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='inclusion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Inclusion'),
        ),
    ]
