# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20160901_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_point', models.CharField(blank=True, max_length=255, null=True)),
                ('tourdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail')),
            ],
        ),
    ]
