# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20160901_1831'),
        ('tours', '0003_importantpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='term_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Term'),
        ),
    ]
