# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_placesinclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerary',
            name='tour_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
