# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20161215_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritinerary',
            name='tour_day_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touritinerary',
            name='tour_day',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
