# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_auto_20161215_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerary',
            name='tour_stays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
