# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 02:56
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160926_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='accounts'),
        ),
    ]
