# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion_type', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_type', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTourExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_tour_exclusion', models.CharField(max_length=250, null=True)),
                ('exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Exclusion')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTourInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_tour_inclusion', models.CharField(max_length=250, null=True)),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Inclusion')),
            ],
        ),
        migrations.CreateModel(
            name='TermNCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_exclusion', models.CharField(max_length=250, null=True)),
                ('exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Exclusion')),
            ],
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_inclusion', models.CharField(max_length=250, null=True)),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Inclusion')),
            ],
        ),
    ]
