# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='termncondition',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Term'),
        ),
    ]
