# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 09:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(max_length=10024, null=True)),
                ('quote', models.TextField(blank=True, max_length=1024, null=True)),
                ('img_content', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blogs')),
                ('img_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('img_credit_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceDescribedInBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placedetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagForBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, null=True, unique=True)),
                ('head_img', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blogs')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expected_time', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(null=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tagforblog',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Title'),
        ),
        migrations.AddField(
            model_name='placedescribedinblog',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Title'),
        ),
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Title'),
        ),
    ]
