# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20160910_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='state_detail',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='title',
            name='blog_type',
            field=models.CharField(choices=[('inspired', 'Be Inspired'), ('photoblog', 'Photo Blog'), ('tips', 'Travel Tips'), ('stories', 'Travel Stories'), ('', 'Any')], max_length=128, null=True),
        ),
    ]
