# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 07:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(max_length=250)),
                ('Comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Short_description', models.TextField(max_length=2000, null=True)),
                ('interested_status', models.CharField(choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested'), ('Highly Interested', 'Highly Interested')], max_length=250, null=True)),
                ('trip_status', models.CharField(choices=[('Booked With Us', 'Booked With Us'), ('Booked With TT', 'Booked With TT'), ('Booked With Others', 'Booked With Others'), ('Trip Canceled', 'Trip Canceled')], max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=250)),
                ('trip_id', models.IntegerField(null=True)),
                ('number_of_adults', models.IntegerField(null=True)),
                ('number_of_children', models.IntegerField(null=True)),
                ('places', models.CharField(max_length=250)),
                ('start_day', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_day', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='tripdetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail'),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='tripdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail'),
        ),
    ]
