# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0002_auto_20161004_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
