# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0003_auto_20161004_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
