# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20160927_0826'),
        ('traveltriangle', '0005_auto_20161005_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDayWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name_with_day', models.CharField(max_length=255)),
                ('detail', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('trip_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuoteGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_short_intro', models.CharField(max_length=255)),
                ('itinerydaywise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.ItineraryDayWise')),
                ('night_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
    ]
