# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0007_auto_20161018_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydaywise',
            name='quote',
        ),
    ]
