# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0008_remove_itinerarydaywise_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotegeneration',
            name='itinerydaywise',
        ),
        migrations.RemoveField(
            model_name='quotegeneration',
            name='night_stay',
        ),
    ]
