# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20160927_0826'),
        ('traveltriangle', '0009_auto_20161018_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotegeneration',
            name='night_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
    ]
