# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0011_auto_20161019_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotegeneration',
            name='quote',
        ),
        migrations.AddField(
            model_name='quotegeneration',
            name='tripdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail'),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='trip_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
