# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0012_auto_20161025_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_id',
            field=models.IntegerField(unique=True),
        ),
    ]
