# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0013_auto_20161025_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='trip_name',
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
