# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0016_auto_20161102_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_number',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='trip_status',
            field=models.CharField(choices=[('Not Booked', 'Not Booked'), ('Booked With Us', 'Booked With Us'), ('Booked With TT', 'Booked With TT'), ('Booked With Others', 'Booked With Others'), ('Trip Cancelled', 'Trip Cancelled')], max_length=250, null=True),
        ),
    ]
