# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0017_auto_20161105_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_number',
            field=models.CharField(max_length=250),
        ),
    ]
