# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0019_auto_20161105_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('tripdetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
    ]
