# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0020_wholeitinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quoted_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='number_of_adults',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='number_of_children',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_nights',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
