# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 06:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0022_auto_20161105_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
