# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-08 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0024_tripdetail_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Short_description',
            new_name='short_description',
        ),
    ]
