# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0025_auto_20161108_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='interested_status',
            field=models.CharField(choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested'), ('Highly Interested', 'Highly Interested'), ('Booked', 'Booked')], max_length=250, null=True),
        ),
    ]
