# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0027_comment_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetail',
            name='pub_date',
        ),
    ]
