# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0028_remove_calldetail_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='pub_date',
        ),
    ]
