# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0031_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholeitinerary',
            name='text',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='wholeitinerary',
            name='tripdetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail'),
        ),
    ]
