# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0033_auto_20161114_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
