# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0034_calldetail_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholeitinerary',
            name='calculation',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='interested_status',
            field=models.CharField(blank=True, choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested'), ('Highly Interested', 'Highly Interested'), ('Booked', 'Booked')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='short_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('Not Booked', 'Not Booked'), ('Booked With Us', 'Booked With Us'), ('Booked With TT', 'Booked With TT'), ('Booked With Others', 'Booked With Others'), ('Trip Cancelled', 'Trip Cancelled')], max_length=250, null=True),
        ),
    ]
