# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20160927_0826'),
        ('traveltriangle', '0035_auto_20161115_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('night_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel')),
            ],
        ),
        migrations.RemoveField(
            model_name='quotegeneration',
            name='itinerydaywise',
        ),
        migrations.RemoveField(
            model_name='quotegeneration',
            name='night_stay',
        ),
        migrations.RemoveField(
            model_name='quotegeneration',
            name='tripdetail',
        ),
        migrations.DeleteModel(
            name='QuoteGeneration',
        ),
        migrations.AddField(
            model_name='itinerarydaywise',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.Itinerary'),
        ),
    ]
