# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0037_auto_20161117_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='itinerarydaywise',
            name='running_kms',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
