# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0039_auto_20161117_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wholeitinerary',
            name='calculation',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
