# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0040_auto_20161121_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=225, null=True)),
                ('room_type', models.CharField(blank=True, max_length=225, null=True)),
                ('room_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('tripdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=225, null=True)),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('price_paid', models.PositiveIntegerField(null=True)),
                ('flight', models.BooleanField(default=False)),
                ('price_paid_for_flight', models.PositiveIntegerField(blank=True, default=0)),
                ('train', models.BooleanField(default=False)),
                ('price_paid_for_train', models.PositiveIntegerField(blank=True, default=0)),
                ('tripdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BookedTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('total_expences', models.PositiveIntegerField(blank=True, null=True)),
                ('tripdetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traveltriangle.TripDetail')),
            ],
        ),
    ]
