# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0041_bookedhotel_bookedtravel_bookedtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='interested_status',
            field=models.CharField(choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested'), ('Highly Interested', 'Highly Interested'), ('Booked', 'Booked')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='trip_status',
            field=models.CharField(choices=[('Not Booked', 'Not Booked'), ('Booked With Us', 'Booked With Us'), ('Booked With TT', 'Booked With TT'), ('Booked With Others', 'Booked With Others'), ('Trip Cancelled', 'Trip Cancelled')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='number_of_adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='person_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='places',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
