# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0044_auto_20161209_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='start_day',
        ),
    ]
