# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0045_remove_tripdetail_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='start_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='trip_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
