# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0049_auto_20161209_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholeitinerary',
            name='tripdetail',
        ),
        migrations.RemoveField(
            model_name='wholeitinerary',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='calculation',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='interested_status',
            field=models.CharField(choices=[('Not Interested', 'Not Interested'), ('Interested', 'Interested'), ('Highly Interested', 'Highly Interested'), ('Booked', 'Booked')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='WholeItinerary',
        ),
    ]
