# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0050_auto_20161209_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='staff_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
