# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0051_tripdetail_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='staff_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
