# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0053_auto_20161209_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='staff_name',
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='staff_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
