# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0057_auto_20161209_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedhotel',
            name='tripdetail',
        ),
        migrations.RemoveField(
            model_name='bookedtravel',
            name='tripdetail',
        ),
        migrations.RemoveField(
            model_name='bookedtrip',
            name='tripdetail',
        ),
        migrations.DeleteModel(
            name='BookedHotel',
        ),
        migrations.DeleteModel(
            name='BookedTravel',
        ),
        migrations.DeleteModel(
            name='BookedTrip',
        ),
    ]
