# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltriangle', '0058_auto_20161211_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
