# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooltrips', '0002_schooltourdetail_term_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_tourdetail_term_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewForSchoolTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, max_length=480, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooltrips.SchoolTourDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewForTours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, max_length=480, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
