# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_placesinclude'),
        ('review', '0003_auto_20160909_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfortours',
            name='tour',
        ),
        migrations.AddField(
            model_name='reviewfortours',
            name='tourdetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.TourDetail'),
        ),
        migrations.AlterField(
            model_name='reviewforhotel',
            name='review_text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reviewforschooltrip',
            name='review_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reviewfortours',
            name='review_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
