# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 06:57
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20160926_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfortours',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='review'),
        ),
    ]
