# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 07:55
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_reviewfortours_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewfortours',
            old_name='image',
            new_name='user_image',
        ),
        migrations.AddField(
            model_name='reviewforschooltrip',
            name='user_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='review'),
        ),
    ]
