# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-05 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetail',
            name='place_detail',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='placedetail',
            name='place_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placedetail',
            name='place_tegline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
