# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160905_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('detail', models.TextField(max_length=10000, null=True)),
                ('placedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('detail', models.TextField(max_length=10000, null=True)),
                ('placedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=250, null=True)),
                ('attraction_detail', models.TextField(max_length=10000, null=True)),
                ('placedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.PlaceDetail')),
            ],
        ),
    ]
