# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_mustdo_placetoeat_placetovisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedetail',
            old_name='place_tegline',
            new_name='place_tagline',
        ),
    ]
