# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20160916_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedetail',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
