# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_howtoreach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtoreach',
            name='transpotation_type',
            field=models.CharField(choices=[('Railway', 'Railway'), ('Air', 'Air'), ('Road', 'Road')], max_length=128, null=True),
        ),
    ]
