# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20161211_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imppoint',
            old_name='name',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='placetovisit',
            old_name='place_img',
            new_name='attraction_img',
        ),
        migrations.AddField(
            model_name='placedetail',
            name='credit_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='placedetail',
            name='credit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedetail',
            name='licence_type',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='credit_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='credit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='licence_type',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placetoeat',
            name='credit_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='placetoeat',
            name='credit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placetoeat',
            name='licence_type',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placetoeat',
            name='place_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='places'),
        ),
        migrations.AlterField(
            model_name='statedetail',
            name='state_name',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Kerala', 'Kerala'), ('Rajasthan', 'Rajasthan'), ('Maharastra', 'Maharastra'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('West Bengal', 'West Bengal'), ('Sikkim', 'Sikkim'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Meghalaya', 'Meghalaya'), ('Andaman & Nicobar', 'Andaman & Nicobar'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Lakshadweep', 'Lakshadweep')], max_length=128, null=True),
        ),
    ]
